### PR TITLE
NetCore support

### PR DESCRIPTION
**Pull request by Davidblkx**

### CODE REVIEW

**Comment by ondfisk** [comment]
Hi David,
If you inspect the other projects in C5, you'll notice that files are linked not added (compare C5 vs C5.NET40 for instance).
Have you changed anything in the files you've added?

Also don't check in the .lock.json file and other generated stuff.

If you can update your request I'll gladly accept it.

**Comment by pmunin** [comment]
any updates on this pull request? 
@ondfisk as far as I know .NET Core project.json does not allow to link files, so it has to be copied  :disappointed:

**Comment by ondfisk** [comment]
.NET Core and .NET Standard have moved (back) to .csproj so I've added a C5.NETCore and a C5.NETStandard project. Not sure if both are needed - does that help? (Haven't updated NuGet yet)

**Comment by pmunin** [comment]
Oh I heard they only plan to, didn't know it was decided.
Yeah just to be safe it's better to have both there.

**Comment by neris** [comment]
You don't have to target `netcoreapp` for a library, it's designed only for executable projects.
Also, please don't just target the highest version of `netstandard`. Use the minimum required version (for your library, I think it would be `netstandard1.3`) so the projects targeting lover standard versions can use it.

**Comment by llint** [comment]
Any status updates on a (possible) beta release of the dotnet core/standard support on NuGet.org?

**Pull request closed without merging**
